### ISSUE TITLE
Devfolio Home

### ISSUE THREAD

**Issue by jawed-salim** [j4w3d/devfolio#1]
Add Screenshot or GIF animation of web app

![home](https://user-images.githubusercontent.com/12079219/88622175-d6d78180-d0bf-11ea-8815-07c3b2651e7b.png)

**Comment by j4w3d** [comment]
Uploaded GIF 

![devfolio](https://user-images.githubusercontent.com/12079219/88623437-96c5ce00-d0c2-11ea-9d1c-ff61643e5775.gif)

**Comment by jawed-salim** [comment]
![jawed](https://user-images.githubusercontent.com/12079219/88625754-0473f900-d0c7-11ea-94b6-aed7882ba93d.gif)

**Comment by j4w3d** [comment]
Done
